name: Pull Request Linter

on:
  pull_request:
    types: [opened,edited,reopened,synchronize]

jobs:
  pr_lint_job:
    runs-on: ubuntu-latest
    name: A job to lint pull requests
    steps:
    - name: Action Step
      id: PRLinter
      uses: Samuel1989/action-test@master
      with:
        who-to-greet: 'Mona the Octocat'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
